### ISSUE TITLE
SSL Certificate expired

### ISSUE THREAD

**Issue by MathieuDR** [osrsbox/osrsbox-api#23]
We cannot do any more API calls because the SSL Certificate is expired.

```
Validity: [From: Fri Oct 29 20:52:02 CEST 2021,
               To: Thu Jan 27 19:52:01 CET 2022]
  Issuer: CN=R3, O=Let's Encrypt, C=US
```

https://api.osrsbox.com/monsters/3010

**Comment by osrsbox** [comment]
Hey @MathieuDR - sorry I let this lapse, am not actively maintaining this project. But I did update the certificate.
